spring.application.name=autonomousCodeMaintenance

# Cohere API
cohere.api.key=${COHERE_API_KEY}

# DB
spring.datasource.url = jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username = postgres
spring.datasource.password = postgres

spring.ai.vectorstore.pgvector.initialize-schema = true

server.port = 8081

#GitHub
github.token=${GITHUB_TOKEN}
github.repo = kuruma007/MessageDecoder
github.base-branch = main